language: python
python:
  - '2.7'
  - '3.4'
  - '3.5'

env:
  - DJANGO=1.10
  - DJANGO=1.11

install:
  - pip install -q Django==$DJANGO
  - pip install coveralls

script:
  - coverage run runtests.py --source social_widgets

after_success:
  - coveralls
